name: DevTrack Production CI/CD

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  IMAGE_NAME: devtrack-platform
  REGISTRY: docker.io

jobs:

  # ===================================
  # BUILD & PUSH DOCKER IMAGE
  # ===================================
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      docker_tag: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  # ===================================
  # DEPLOY TO EC2 USING OIDC + SSM
  # ===================================
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::074122282902:role/devtract_role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: DevTrackDeploySession

      - name: Deploy via SSM
        run: |

          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --comment "DevTrack Docker Deployment" \
            --parameters commands="[
              \"set -e\",
              \"export DOCKER_USER=${{ secrets.DOCKERHUB_USERNAME }}\",
              \"export DOCKER_PASS=${{ secrets.DOCKERHUB_PASSWORD }}\",
              \"export TAG=${{ needs.build-and-push.outputs.docker_tag }}\",
              \"echo \$DOCKER_PASS | docker login docker.io -u \$DOCKER_USER --password-stdin\",
              \"docker pull docker.io/\$DOCKER_USER/devtrack-platform:\$TAG\",
              \"docker stop devtrack-container || true\",
              \"docker rm devtrack-container || true\",
              \"docker run -d --name devtrack-container -p 80:5000 docker.io/\$DOCKER_USER/devtrack-platform:\$TAG\",
              \"docker image prune -af || true\"
            ]" \
            --query "Command.CommandId" \
            --output text \
            --region ${{ env.AWS_REGION }})

          aws ssm wait command-executed \
            --command-id $COMMAND_ID \
            --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
            --region ${{ env.AWS_REGION }}
